import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ページの生成された時間を取得
  const time = new Date().toLocaleString();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <div>{children}</div>
          <div className={styles.grid}>
            <Link href="/" className={styles.card}>
              <h2>
                Top <span>-&gt;</span>
              </h2>
              <p>{time}</p>
            </Link>
            <Link href="/static/" className={styles.card}>
              <h2>
                Static <span>-&gt;</span>
              </h2>
              <p>SSG</p>
            </Link>
            <Link href="/dynamic/" className={styles.card}>
              <h2>
                Dynamic <span>-&gt;</span>
              </h2>
              <p>SSR</p>
            </Link>
            <Link href="/suspense/" className={styles.card}>
              <h2>
                Suspense <span>-&gt;</span>
              </h2>
              <p>SSR(parts)</p>
            </Link>
          </div>
        </main>
      </body>
    </html>
  );
}
